apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-chaos
spec:
  appinfo:
    appns: 'default'
    applabel: 'app=nginx'
    appkind: 'deployment'
  # It can be active/stop
  engineState: 'active'
  #ex. values: ns1:name=percona,ns2:run=nginx
  auxiliaryAppInfo: ''
  chaosServiceAccount: infra-elasticcache-failover-sa
  # It can be delete/retain
  jobCleanUpPolicy: 'delete'
  experiments:
    - name: infra-elasticcache-failover
      spec:
        components:
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '30'

            # set chaos interval (in sec) as desired
            - name: CHAOS_INTERVAL
              value: '10'
              
            # ELASTICCACHE_CLUSTER_NAME
            - name: ELASTICCACHE_CLUSTER_NAME
              value: ''
            
            # MIN_NODES
            - name: MIN_NODES
              value: '2'
            
            # ENABLE_AUTOFAILOVER
            - name: ENABLE_AUTOFAILOVER
              value: "True"
