apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    it will failover elasticcache, waits for the chaos duration and reverts the chaos
kind: ChaosExperiment
metadata:
  name: ec-failover
  labels:
    name: ec-failover
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: chaosexperiment
    app.kubernetes.io/version: latest
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups: 
          - "" 
          - "batch" 
          - "apps" 
          - "litmuschaos.io" 
        resources: 
          - "jobs" 
          - "pods" 
          - "pods/log" 
          - "events" 
          - "deployments" 
          - "replicasets" 
          - "pods/exec" 
          - "chaosengines" 
          - "chaosexperiments" 
          - "chaosresults" 
        verbs: 
          - "create" 
          - "list" 
          - "get" 
          - "patch" 
          - "update" 
          - "delete" 
          - "deletecollection" 
    image: "asappinc/litmus-py-runner:latest"
    imagePullPolicy: Always
    args:
    - -c
    - python3 -u experiment -name=infra-elasticcache-failover
    command:
    - /bin/bash
    env:

    - name: TOTAL_CHAOS_DURATION
      value: '300' 

    - name: CHAOS_INTERVAL
      value: '100'

    - name: LIB
      value: 'litmus'

    - name: RAMP_TIME
      value: '60'

    - name: ELASTICCACHE_CLUSTER_NAME
      value: ''
    
    - name: MIN_NODES
      value: '2'
    
    - name: ENABLE_AUTOFAILOVER
      value: 'True'

    - name: AWS_DEFAULT_REGION
      value: 'us-east-1'
      
    labels:
      name: ec-failover
      app.kubernetes.io/part-of: litmus
      app.kubernetes.io/component: experiment-job
      app.kubernetes.io/version: latest 