---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-elasticcache-failover-sa
  namespace: litmus
  labels:
    name: infra-elasticcache-failover-sa
    app.kubernetes.io/part-of: litmus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: infra-elasticcache-failover-sa
  namespace: litmus
  labels:
    name: infra-elasticcache-failover-sa
    app.kubernetes.io/part-of: litmus
rules:
  - apiGroups: 
      - "" 
      - "batch" 
      - "apps" 
      - "litmuschaos.io" 
    resources: 
      - "jobs" 
      - "pods" 
      - "pods/log" 
      - "events" 
      - "deployments" 
      - "replicasets" 
      - "pods/exec" 
      - "chaosengines" 
      - "chaosexperiments" 
      - "chaosresults" 
    verbs: 
      - "create" 
      - "list" 
      - "get" 
      - "patch" 
      - "update" 
      - "delete" 
      - "deletecollection" 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infra-elasticcache-failover-sa
  namespace: litmus
  labels:
    name: infra-elasticcache-failover-sa
    app.kubernetes.io/part-of: litmus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infra-elasticcache-failover-sa
subjects:
- kind: ServiceAccount
  name: infra-elasticcache-failover-sa
  namespace: litmus